[package]
name = "step_2_2"
version = "0.1.0"
edition = "2024"
publish = false

[[bench]]
name = "mem_replace_benchmark"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
